repos:
  - repo: local
    hooks:
      - id: cmake-format
        name: cmake-format
        entry: cmake-format -i
        language: system
        args: [ --check ]
        files: ^(CMakeLists\.txt|.*\.cmake)$
